server {
    listen 80;

    # This handles the static React files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This line is CRITICAL for React Router to work
        try_files $uri $uri/ /index.html;
    }

    # NOTE: We do NOT put a /api/ block here. 
    # The AWS Load Balancer handles that routing.
}
